Add some tests to increase coverage
namehash/nameguard pull request #100
Opened 2023-11-02 13:26 UTC by Byczong

2023-11-02 17:48 UTC, Carbon225 commented on api/tests/test_nameguard.py
> +    assert GenericCheckResult(**{'check': Check.NORMALIZED, 'status': CheckStatus.INFO, '_name_message': ''}) == \
Why the dictionary?

2023-11-02 17:51 UTC, Carbon225 requested changes
```python
GenericCheckResult(**{'check': Check.NORMALIZED, 'status': CheckStatus.INFO, '_name_message': ''})
```
?

2023-11-02 19:19 UTC, Byczong commented on api/tests/test_nameguard.py
> +    assert GenericCheckResult(**{'check': Check.NORMALIZED, 'status': CheckStatus.INFO, '_name_message': ''}) == \
I changed it to keywords

2023-11-02 20:23 UTC, djstrong commented on api/tests/test_checks.py
> +    assert CheckStatus.WARN >= CheckStatus.WARN
is it ok?

2023-11-02 20:25 UTC, Carbon225 commented on api/tests/test_checks.py
> +    assert CheckStatus.WARN >= CheckStatus.WARN
Yes

2023-11-02 22:44 UTC, Carbon225 requested changes

2023-11-02 22:44 UTC, Carbon225 commented on api/tests/test_nameguard.py
> +    assert repr(GenericCheckResult(**{'check': Check.NORMALIZED, 'status': CheckStatus.PASS, '_name_message': ''})) == \
```suggestion
    assert repr(GenericCheckResult(check=Check.NORMALIZED, status=CheckStatus.PASS, _name_message='')) == \
```

2023-11-02 22:47 UTC, Carbon225 approved these changes

2023-11-03 10:00 UTC, notrab approved these changes

2023-11-03 15:50 UTC, merged