python publish workflow
namehash/nameguard pull request #98
Opened 2023-11-01 11:06 UTC by Carbon225

2023-11-01 12:39 UTC, djstrong requested changes
It is in subdirectory

2023-11-01 12:40 UTC, djstrong commented
Add also authors to toml

2023-11-02 22:48 UTC, Carbon225 commented
@djstrong ok?

2023-11-02 23:04 UTC, djstrong approved these changes
we need to try

2023-11-03 15:52 UTC, merged